sudo: false
language: node_js

node_js:
  - "0.12"
  - "4.2.4"
  - "5.4.1"

env:
  - NODE_ENV=development

services:
  - mongodb

before_install:
  - npm i -g bower
  - mongoimport --db beers --collection beers --jsonArray step1/beer-list.json
  - npm install -g mocha
